apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculadora
spec:
  selector:
    matchLabels:
      app: calculadora
  template:
    metadata:
      labels:
        app: calculadora
    spec:
      containers:
      - name: calculadora
        image: felipejm91/calculadora-flask-python:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000
