apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: calculadora 
spec:
  ingressClassName: nginx
  rules:
  - host: calc.felipemeneguetti.com.br
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: calculadora-service
              port: 
                number: 80                          
            
