apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: calculadora 
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #UTILIZA CERTIFICADO DE TESTE
    #cert-manager.io/issuer: "letsencrypt-dev"
    #UTILIZA CERTIFICADO DE PRODUÇÃO
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - calc.felipemeneguetti.com.br
    #UTILIZA CERTIFICADO DE TESTE
    #secretName: secret-tls-dev
    #UTILIZA CERTIFICADO DE PRODUÇÃO
    secretName: secret-tls-prod
  rules:
  - host: calc.felipemeneguetti.com.br
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: calculadora-service
              port: 
                number: 80                          
            
