apiVersion: v1
kind: Service
metadata:
  name: calculadora-service
  namespace: calculadora
spec:
  selector:
    app: calculadora
  ports:
  - port: 5000
    targetPort: 5000
  type: LoadBalancer
