name: Criar e Publicar Imagem Docker

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:          
    # Realiza Login no repositório Docker
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.USER }}
        password: ${{ secrets.TOKEN }}
        
    # Pega Tag para versionar container
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: felipejm91/calculadora-flask-python 
       
    # Realiza construção da imagem e Push para Docker Hub       
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag felipejm91/calculadora-flask-python:${{ steps.meta.outputs.tags }} && docker push      
