name: CI Container Docker

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:          
    # Realiza Login no repositório Docker
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.USER }}
        password: ${{ secrets.TOKEN }}
        
    # Gera tag para imagem   
    - name: Docker Metadata action
      uses: docker/metadata-action@v4.0.1
      id: tag_cont
      with:
        # List of Docker images to use as base name for tags
        images: felipejm91/calculadora-flask-python   
      
    # Realiza construção da imagem e Push para Docker Hub       
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.tag_cont.outputs.tags }}
