name: CI Container Docker

on:
  push:
    branches: 
      - 'main'
    tags:
      - 'v*'

env:
  REPOSITORIO: felipejm91
  IMAGEM_NOME: calculadora-flask-python

jobs:

  build:

    runs-on: ubuntu-latest

    steps:          
    
    - name: Checkout
      uses: actions/checkout@v3.1.0
    
    #Pega metadados para utilizar na build do container
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REPOSITORIO }}/${{ env.IMAGEM_NOME }}
        tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
    
    # Realiza Login no repositório Docker
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.USER }}
        password: ${{ secrets.TOKEN }}
 
    #Realiza build e push da imagem do container
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
          
