name: CI Container Docker

on:
  push:
    branches: [ "main" ]

env:
  REPOSITORIO: felipejm91
  IMAGEM_NOME: calculadora-flask-python

jobs:

  build:

    runs-on: ubuntu-latest

    steps:          
    #Pega metadados para utilizar na build do container
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REPOSITORIO }}/${{ env.IMAGEM_NOME }}
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    
    # Realiza Login no repositório Docker
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.USER }}
        password: ${{ secrets.TOKEN }}
        registry: ${{ env.REPOSITORIO }}
             
    # Realiza construção da imagem e Push para Docker Hub       
    - name: Build and Push the Docker image      
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
