name: CI Container Docker

on:
  push:
    branches: [ "main" ]

env:
  REPOSITORIO: felipejm91
  IMAGEM_NOME: calculadora-flask-python

jobs:

  build:

    runs-on: ubuntu-latest

    steps:          
    #Pega metadados para utilizar na build do container
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REPOSITORIO }}/${{ env.IMAGEM_NOME }}        
    
    #Pegar SHA curto
    - name: Set short git commit SHA
      id: shashort
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "::set-output name=short_sha::$calculatedSha"
    
    # Realiza Login no repositório Docker
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.USER }}
        password: ${{ secrets.TOKEN }}
        #registry: ${{ env.REPOSITORIO }}
             
    # Realiza construção da imagem e Push para Docker Hub       
    - uses: actions/checkout@v3.1.0
    - name: Build and Push the Docker image      
      run: |
        docker build . --file Dockerfile --tag ${{ env.REPOSITORIO }}/${{ env.IMAGEM_NOME }}:latest && docker push ${{ env.REPOSITORIO }}/${{ env.IMAGEM_NOME }}:latest
        docker build . --file Dockerfile --tag ${{ env.REPOSITORIO }}/${{ env.IMAGEM_NOME }}:${{ steps.shashort.outputs.short_sha }} && docker push ${{ env.REPOSITORIO }}/${{ env.IMAGEM_NOME }}:${{ steps.shashort.outputs.short_sha }}

