name: CI Container Docker

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:          
    # Realiza Login no repositório Docker
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.USER }}
        password: ${{ secrets.TOKEN }}
       
    # Constrói e faz push do container para o Docker Hub
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        # Apontamento para arquivo do Dockerfile
        file: ./Dockerfile
        push: true
        tags: 
          felipejm91/calculadora-flask-python:latest
          felipejm91/calculadora-flask-python:${{ github.run_number }}
        
