name: CI Container Docker

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:          
    #Pega metadados para utilizar na build do container
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: name/app
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    
    # Realiza Login no repositório Docker
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.USER }}
        password: ${{ secrets.TOKEN }}
             
    # Realiza construção da imagem e Push para Docker Hub       
    - uses: actions/checkout@v3
    - name: Build the Docker image      
      run: |
        docker build . --file Dockerfile --tag felipejm91/calculadora-flask-python:${{ steps.meta.outputs.tags }} && docker push felipejm91/calculadora-flask-python:${{ steps.meta.outputs.tags }}
