name: CI Container Docker

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:          
    # Realiza Login no repositório Docker
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.USER }}
        password: ${{ secrets.TOKEN }}
        
    # Gera tag para imagem   
    - name: Docker Metadata action
      uses: docker/metadata-action@v4.0.1
      id: tag_cont
      with:
        # List of Docker images to use as base name for tags
        images: felipejm91/calculadora-flask-python   
      
    # Realiza construção da imagem e Push para Docker Hub       
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag felipejm91/calculadora-flask-python:latest && docker push felipejm91/calculadora-flask-python:latest
        docker build . --file Dockerfile ${{ steps.tag_cont.outputs.tags }}${{ steps.tag_cont.outputs.tags }} && docker push ${{ steps.tag_cont.outputs.tags }}
